name: Deploy Dockerized App to EC2

on:
  push:
    branches:
      - master  

env:
  CLUSTER_NAME: demoec2
  SERVICE_NAME: demo-service
  TASK_DEF_FAMILY: demo-task
  CONTAINER_NAME: demo-container
  #ECR_REPO: your-ecr-repo-name
  IMAGE_TAG: ${{github.sha}}

  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

    - name: Github Workspace
      run: echo ${{ github.workspace }}

    - name: Confirm git commit SHA output
      run: echo ${{ env.COMMIT_SHORT_SHA }}
        
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build JAR with Maven
      run: mvn clean package -DskipTests

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

    - name: Build, tag, and push Docker image to ECR
      run: |
        #IMAGE_TAG=latest123
        docker build -t ${{ secrets.ECR_REPOSITORY }}:${{ env.COMMIT_SHORT_SHA }} .
        docker push ${{ secrets.ECR_REPOSITORY }}:${{ env.COMMIT_SHORT_SHA }}


    - name: Create ECS cluster if not exists
      run: |
        CLUSTER_CHECK=$(aws ecs describe-clusters --clusters $CLUSTER_NAME \
        --query "clusters[0].status" --output text || echo "MISSING")

        if [ "$CLUSTER_CHECK" = "MISSING" ] || [ "$CLUSTER_CHECK" = "None" ]; then
          echo "Cluster not found. Creating ECS cluster..."
          aws ecs create-cluster --cluster-name $CLUSTER_NAME
        else
          echo "ECS cluster '$CLUSTER_NAME' already exists."
        fi

    - name: Prepare updated task definition
      id: task-def
      run: |
        IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ env.COMMIT_SHORT_SHA }}"
        sed "s|REPLACE_ME|$IMAGE_URI|g" ecs-task-def.json > final-task-def.json

    - name: Register new task definition
      run: |
        TASK_DEF_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://final-task-def.json \
          --query 'taskDefinition.taskDefinitionArn' \
          --output text)
        echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

    - name: Create or update ECS service
      run: |
       SERVICE_EXISTS=$(aws ecs describe-services \
         --cluster demoec2 \
         --services demo-service \
         --query "services[0].serviceName" \
         --output text 2>/dev/null || echo "None")

       if [ "$SERVICE_EXISTS" = "None" ]; then
         echo "Creating ECS service..."
         aws ecs create-service \
        --cluster demoec2 \
        --service-name demo-service \
        --task-definition my-task-def-name \
        --launch-type EC2 \
        --desired-count 1 \
        --deployment-controller type=ECS \
        --network-configuration "awsvpcConfiguration={subnets=[subnet-xxx],securityGroups=[sg-xxx],assignPublicIp=ENABLED}"
       else
        echo "Updating ECS service..."
        aws ecs update-service \
        --cluster demoec2 \
        --service demo-service \
        --task-definition my-task-def-name
       fi


